#
# Copyright (C) 2023 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

name: libdyntype CI

on:
  push:
    paths:
      - "runtime-library/**"
  pull_request:
    paths:
      - "runtime-library/**"
  # allow to be triggered manually
  workflow_dispatch:

jobs:
  build_and_test:
    name: 'Libdyntype Build and Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: runtime-library/libdyntype

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
          submodules: true

      - name: download dependencies
        run: |
          ./download.sh
        working-directory: runtime-library/deps

      - name: Dyntype Build
        run: |
          mkdir build && cd build
          cmake .. && make

      - name: Dyntype Test
        run: |
          cd test
          mkdir build && cd build
          cmake .. -DUNITTEST_USE_SANITIZER=1
          make
          make test
