#
# Copyright (C) 2023 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

name: ts2wasm-compiler CI

on:
  push:
    paths-ignore:
      - "doc/**"
      - "README.md"
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "doc/**"
      - "README.md"
  # allow to be triggered manually
  workflow_dispatch:

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
        # Test the latest version of Node.js plus the last two LTS versions.
        # node-version:
        #   - "*"
        #   - lts/*
        #   - lts/-1
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Linter
        run: npx lint-staged

  validate_compilation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - run: npm install

      - name: Test compilation
        run:
          npm run test

  validate_execution:
    needs:
      [install_dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          "X86_64", "X86_32"
        ]
        simple_libdyntype: [
          1, 0
        ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      
      - name: Use node version 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: download dependencies
        run: |
          ./download.sh
          sudo apt update && sudo apt install g++-multilib -y
        working-directory: runtime-library/deps

      - name: Build runtime
        run: |
          mkdir build && cd build
          cmake .. -DWAMR_BUILD_TARGET=${{ matrix.target }} -DUSE_SIMPLE_LIBDYNTYPE=${{ matrix.simple_libdyntype }} -DWAMR_GC_IN_EVERY_ALLOCATION=1 -DUSE_SANITIZER=1 && make -j$(nproc)
        working-directory: runtime-library/

      - name: Validate execution
        run:
          SIMPLE_LIBDYNTYPE=${{ matrix.simple_libdyntype }} npm start
        working-directory: tools/validate/wamr
